FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node ./client/package.json /home/node/app

RUN npm install

COPY --chown=node:node ./client ./

CMD ["npm","run","start"]