sudo: required
language: generic 

services:
   - docker

before_install:
  - docker build -t anvithaprabhu98/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true anvithaprabhu8/react-test npm test

after_success:
  -  docker build -t anvithaprabhu98/multi-clientt ./client
  -  docker build -t anvithaprabhu98/multi-nginxx ./nginx
  -  docker build -t anvithaprabhu98/multi-serverr ./server
  -  docker build -t anvithaprabhu98/multi-workerr ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push anvithaprabhu98/multi-clientt
  - docker push anvithaprabhu98/multi-nginxx
  - docker push anvithaprabhu98/multi-serverr
  - docker push anvithaprabhu98/multi-workerr
