sudo: required
language: generic 

services:
   - docker

before_install:
  - docker build -t anvithaprabhu8/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true anvithaprabhu8/react-test npm test

after_success:
  -  docker build -t anvithaprabhu8/multi-client ./client
  -  docker build -t anvithaprabhu8/multi-nginx ./nginx
  -  docker build -t anvithaprabhu8/multi-server ./server
  -  docker build -t anvithaprabhu8/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push anvithaprabhu8/multi-client
  - docker push anvithaprabhu8/multi-nginx
  - docker push anvithaprabhu8/multi-server
  - docker push anvithaprabhu8/multi-worker
